// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eBroker.DataAccess;

namespace eBroker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211225183652_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eBroker.Models.Equity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Equities");
                });

            modelBuilder.Entity("eBroker.Models.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EquityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("TraderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquityId");

                    b.HasIndex("TraderId");

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("eBroker.Models.Trader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("eBroker.Models.Holding", b =>
                {
                    b.HasOne("eBroker.Models.Equity", "Equity")
                        .WithMany()
                        .HasForeignKey("EquityId");

                    b.HasOne("eBroker.Models.Trader", null)
                        .WithMany("Holdings")
                        .HasForeignKey("TraderId");

                    b.Navigation("Equity");
                });

            modelBuilder.Entity("eBroker.Models.Trader", b =>
                {
                    b.Navigation("Holdings");
                });
#pragma warning restore 612, 618
        }
    }
}
